const { resolve } = require("path");
const { defineConfig } = require("vite");

module.exports = defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        "1-Three.js_Bruno_Simon": resolve(__dirname, "src/1-Three.js_Bruno_Simon/index.html"),
        "1-Three.js_Bruno_Simon/03-basic-scene": resolve(__dirname, "src/1-Three.js_Bruno_Simon/03-basic-scene/index.html"),
        "1-Three.js_Bruno_Simon/05-transforms-objects": resolve(__dirname, "src/1-Three.js_Bruno_Simon/05-transforms-objects/index.html"),
        "1-Three.js_Bruno_Simon/06-animations": resolve(__dirname, "src/1-Three.js_Bruno_Simon/06-animations/index.html"),
        "1-Three.js_Bruno_Simon/07-cameras": resolve(__dirname, "src/1-Three.js_Bruno_Simon/07-cameras/index.html"),
        "1-Three.js_Bruno_Simon/08-fullscreen-and-resizing": resolve(__dirname, "src/1-Three.js_Bruno_Simon/08-fullscreen-and-resizing/index.html"),
        "1-Three.js_Bruno_Simon/09-geometries": resolve(__dirname, "src/1-Three.js_Bruno_Simon/09-geometries/index.html"),
        "1-Three.js_Bruno_Simon/10-debug-ui": resolve(__dirname, "src/1-Three.js_Bruno_Simon/10-debug-ui/index.html"),
        "1-Three.js_Bruno_Simon/11-textures": resolve(__dirname, "src/1-Three.js_Bruno_Simon/11-textures/index.html"),
        "1-Three.js_Bruno_Simon/12-material": resolve(__dirname, "src/1-Three.js_Bruno_Simon/12-material/index.html"),
        "1-Three.js_Bruno_Simon/13-3d-text": resolve(__dirname, "src/1-Three.js_Bruno_Simon/13-3d-text/index.html"),
        "1-Three.js_Bruno_Simon/14-lights": resolve(__dirname, "src/1-Three.js_Bruno_Simon/14-lights/index.html"),
        "1-Three.js_Bruno_Simon/15-shadows": resolve(__dirname, "src/1-Three.js_Bruno_Simon/15-shadows/index.html"),
        "1-Three.js_Bruno_Simon/16-haunted-house": resolve(__dirname, "src/1-Three.js_Bruno_Simon/16-haunted-house/index.html"),
        "1-Three.js_Bruno_Simon/17-particles": resolve(__dirname, "src/1-Three.js_Bruno_Simon/17-particles/index.html"),
        "1-Three.js_Bruno_Simon/18-galaxy-generator": resolve(__dirname, "src/1-Three.js_Bruno_Simon/18-galaxy-generator/index.html"),
        "1-Three.js_Bruno_Simon/19-ray-caster": resolve(__dirname, "src/1-Three.js_Bruno_Simon/19-ray-caster/index.html"),
        "1-Three.js_Bruno_Simon/20-physics": resolve(__dirname, "src/1-Three.js_Bruno_Simon/20-physics/index.html"),
        "1-Three.js_Bruno_Simon/21-import-models": resolve(__dirname, "src/1-Three.js_Bruno_Simon/21-import-models/index.html"),
        "1-Three.js_Bruno_Simon/22-custom-models-with-blender": resolve(__dirname, "src/1-Three.js_Bruno_Simon/22-custom-models-with-blender/index.html"),
        "1-Three.js_Bruno_Simon/23-realistic-render": resolve(__dirname, "src/1-Three.js_Bruno_Simon/23-realistic-render/index.html"),
        "1-Three.js_Bruno_Simon/24-shaders": resolve(__dirname, "src/1-Three.js_Bruno_Simon/24-shaders/index.html"),
        "1-Three.js_Bruno_Simon/25-shader-patterns": resolve(__dirname, "src/1-Three.js_Bruno_Simon/25-shader-patterns/index.html"),
        "1-Three.js_Bruno_Simon/26-raging-sea": resolve(__dirname, "src/1-Three.js_Bruno_Simon/26-raging-sea/index.html"),
        "1-Three.js_Bruno_Simon/27-animated-galaxy": resolve(__dirname, "src/1-Three.js_Bruno_Simon/27-animated-galaxy/index.html"),
        "1-Three.js_Bruno_Simon/28-modified-materials": resolve(__dirname, "src/1-Three.js_Bruno_Simon/28-modified-materials/index.html"),
        "1-Three.js_Bruno_Simon/29-post-processing": resolve(__dirname, "src/1-Three.js_Bruno_Simon/29-post-processing/index.html"),
        "1-Three.js_Bruno_Simon/30-performance-tips": resolve(__dirname, "src/1-Three.js_Bruno_Simon/30-performance-tips/index.html"),

        "2-Three.js_Fundamentals": resolve(__dirname, "src/2-Three.js_Fundamentals/index.html"),
        "2-Three.js_Fundamentals/1-Basics": resolve(__dirname, "src/2-Three.js_Fundamentals/1-Basics/index.html"),
        "2-Three.js_Fundamentals/1-Basics/1-Fundamentals": resolve(__dirname, "src/2-Three.js_Fundamentals/1-Basics/1-Fundamentals/index.html"),
        "2-Three.js_Fundamentals/1-Basics/2-Responsive_Design": resolve(__dirname, "src/2-Three.js_Fundamentals/1-Basics/2-Responsive_Design/index.html"),
        "2-Three.js_Fundamentals/2-Fundamentals": resolve(__dirname, "src/2-Three.js_Fundamentals/2-Fundamentals/index.html"),
        "2-Three.js_Fundamentals/2-Fundamentals/1-Primitives": resolve(__dirname, "src/2-Three.js_Fundamentals/2-Fundamentals/1-Primitives/index.html"),

        "practice-project": resolve(__dirname, "src/practice-project/index.html"),
        "practice-project/audio_visualizer": resolve(__dirname, "src/practice-project/audio_visualizer/index.html"),
        "practice-project/axe": resolve(__dirname, "src/practice-project/axe/index.html"),
        "practice-project/car": resolve(__dirname, "src/practice-project/car/index.html"),
        "practice-project/chair": resolve(__dirname, "src/practice-project/chair/index.html"),
        "practice-project/fence": resolve(__dirname, "src/practice-project/fence/index.html"),
        "practice-project/font_car_physics": resolve(__dirname, "src/practice-project/font_car_physics/index.html"),
        "practice-project/got-north-wall": resolve(__dirname, "src/practice-project/got-north-wall/index.html"),
        "practice-project/opening_website": resolve(__dirname, "src/practice-project/opening_website/index.html"),
        "practice-project/scene_class": resolve(__dirname, "src/practice-project/scene_class/index.html"),
        "practice-project/tech-stack": resolve(__dirname, "src/practice-project/tech-stack/index.html"),
        "practice-project/test_cube": resolve(__dirname, "src/practice-project/test_cube/index.html"),
        "practice-project/text": resolve(__dirname, "src/practice-project/text/index.html"),
        "practice-project/text_animation": resolve(__dirname, "src/practice-project/text_animation/index.html"),
        "practice-project/tree": resolve(__dirname, "src/practice-project/tree/index.html"),
        "practice-project/unroll-image": resolve(__dirname, "src/practice-project/unroll-image/index.html"),
        "practice-project/web_audio_api": resolve(__dirname, "src/practice-project/web_audio_api/index.html"),
      },
    },
  },
});